//! Bulk operations for GatewayTransaction entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateGatewayTransactionDto;
use crate::application::service::GatewayTransactionService;
use crate::domain::entity::GatewayTransaction;

/// Bulk operation handler for GatewayTransaction entities.
///
/// Wraps `GatewayTransactionService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type GatewayTransactionBulkService = GenericBulkService<GatewayTransaction, CreateGatewayTransactionDto, GatewayTransactionService>;

// <<< CUSTOM
// END CUSTOM
