//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod gateway_transaction_bulk;
pub mod payment_gateway_provider_bulk;

pub use gateway_transaction_bulk::GatewayTransactionBulkService;
pub use payment_gateway_provider_bulk::PaymentGatewayProviderBulkService;

// <<< CUSTOM
// END CUSTOM
