//! Bulk operations for PaymentGatewayProvider entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreatePaymentGatewayProviderDto;
use crate::application::service::PaymentGatewayProviderService;
use crate::domain::entity::PaymentGatewayProvider;

/// Bulk operation handler for PaymentGatewayProvider entities.
///
/// Wraps `PaymentGatewayProviderService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type PaymentGatewayProviderBulkService = GenericBulkService<PaymentGatewayProvider, CreatePaymentGatewayProviderDto, PaymentGatewayProviderService>;

// <<< CUSTOM
// END CUSTOM
