//! GatewayTransaction DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::GatewayTransaction;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::GatewayDirection;
use crate::domain::entity::GatewayPartyType;
use crate::domain::entity::GatewayPostingState;
use crate::domain::entity::GatewayProviderCode;
use crate::domain::entity::GatewayTransactionStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new GatewayTransaction
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateGatewayTransactionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "provider_id")]
    pub provider_id: Uuid,
    #[serde(alias = "provider_code")]
    pub provider_code: GatewayProviderCode,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "provider_transaction_id")]
    pub provider_transaction_id: String,
    pub direction: GatewayDirection,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_type")]
    pub party_type: Option<GatewayPartyType>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[serde(alias = "gross_amount")]
    pub gross_amount: Decimal,
    #[serde(alias = "fee_amount")]
    pub fee_amount: Decimal,
    #[serde(alias = "net_amount")]
    pub net_amount: Decimal,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub status: GatewayTransactionStatus,
    #[serde(alias = "posting_state")]
    pub posting_state: GatewayPostingState,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "payment_entry_id")]
    pub payment_entry_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "fee_post_id")]
    pub fee_post_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "settled_at")]
    pub settled_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reference_no")]
    pub reference_no: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "raw_payload")]
    pub raw_payload: Option<serde_json::Value>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a GatewayTransaction
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateGatewayTransactionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "provider_id")]
    pub provider_id: Uuid,
    #[serde(alias = "provider_code")]
    pub provider_code: GatewayProviderCode,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "provider_transaction_id")]
    pub provider_transaction_id: String,
    pub direction: GatewayDirection,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_type")]
    pub party_type: Option<GatewayPartyType>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[serde(alias = "gross_amount")]
    pub gross_amount: Decimal,
    #[serde(alias = "fee_amount")]
    pub fee_amount: Decimal,
    #[serde(alias = "net_amount")]
    pub net_amount: Decimal,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub status: GatewayTransactionStatus,
    #[serde(alias = "posting_state")]
    pub posting_state: GatewayPostingState,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "payment_entry_id")]
    pub payment_entry_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "fee_post_id")]
    pub fee_post_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "settled_at")]
    pub settled_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reference_no")]
    pub reference_no: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "raw_payload")]
    pub raw_payload: Option<serde_json::Value>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a GatewayTransaction
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchGatewayTransactionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "provider_id")]
    pub provider_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "provider_code")]
    pub provider_code: Option<GatewayProviderCode>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "provider_transaction_id")]
    pub provider_transaction_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub direction: Option<GatewayDirection>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "party_type")]
    pub party_type: Option<GatewayPartyType>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "gross_amount")]
    pub gross_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "fee_amount")]
    pub fee_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "net_amount")]
    pub net_amount: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<GatewayTransactionStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "posting_state")]
    pub posting_state: Option<GatewayPostingState>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "payment_entry_id")]
    pub payment_entry_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "fee_post_id")]
    pub fee_post_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "settled_at")]
    pub settled_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "reference_no")]
    pub reference_no: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "raw_payload")]
    pub raw_payload: Option<serde_json::Value>,
}

impl PatchGatewayTransactionDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.provider_id.is_some() || self.provider_code.is_some() || self.provider_transaction_id.is_some() || self.direction.is_some() || self.party_type.is_some() || self.party_id.is_some() || self.gross_amount.is_some() || self.fee_amount.is_some() || self.net_amount.is_some() || self.currency.is_some() || self.status.is_some() || self.posting_state.is_some() || self.payment_entry_id.is_some() || self.fee_post_id.is_some() || self.settled_at.is_some() || self.reference_no.is_some() || self.raw_payload.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for GatewayTransaction entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GatewayTransactionResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub provider_id: Uuid,
    pub provider_code: GatewayProviderCode,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub provider_transaction_id: String,
    pub direction: GatewayDirection,
    pub party_type: Option<GatewayPartyType>,
    pub party_id: Option<Uuid>,
    pub gross_amount: Decimal,
    pub fee_amount: Decimal,
    pub net_amount: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub status: GatewayTransactionStatus,
    pub posting_state: GatewayPostingState,
    pub payment_entry_id: Option<Uuid>,
    pub fee_post_id: Option<Uuid>,
    pub settled_at: Option<DateTime<Utc>>,
    pub reference_no: Option<String>,
    pub raw_payload: Option<serde_json::Value>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for GatewayTransaction entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GatewayTransactionListResponseDto {
    /// List of items
    pub items: Vec<GatewayTransactionResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl GatewayTransactionListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<GatewayTransactionResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GatewayTransactionSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub provider_id: Uuid,
    pub provider_code: GatewayProviderCode,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<GatewayTransaction> for GatewayTransactionResponseDto {
    fn from(entity: GatewayTransaction) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            provider_id: entity.provider_id,
            provider_code: entity.provider_code,
            provider_transaction_id: entity.provider_transaction_id,
            direction: entity.direction,
            party_type: entity.party_type,
            party_id: entity.party_id,
            gross_amount: entity.gross_amount,
            fee_amount: entity.fee_amount,
            net_amount: entity.net_amount,
            currency: entity.currency,
            status: entity.status,
            posting_state: entity.posting_state,
            payment_entry_id: entity.payment_entry_id,
            fee_post_id: entity.fee_post_id,
            settled_at: entity.settled_at,
            reference_no: entity.reference_no,
            raw_payload: entity.raw_payload,
            metadata: entity.metadata,
        }
    }
}

impl From<GatewayTransaction> for GatewayTransactionSummaryDto {
    fn from(entity: GatewayTransaction) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            provider_id: entity.provider_id,
            provider_code: entity.provider_code,
            created_at,
        }
    }
}

impl From<CreateGatewayTransactionDto> for GatewayTransaction {
    fn from(dto: CreateGatewayTransactionDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            provider_id: dto.provider_id,
            provider_code: dto.provider_code,
            provider_transaction_id: dto.provider_transaction_id,
            direction: dto.direction,
            party_type: dto.party_type,
            party_id: dto.party_id,
            gross_amount: dto.gross_amount,
            fee_amount: dto.fee_amount,
            net_amount: dto.net_amount,
            currency: dto.currency,
            status: dto.status,
            posting_state: dto.posting_state,
            payment_entry_id: dto.payment_entry_id,
            fee_post_id: dto.fee_post_id,
            settled_at: dto.settled_at,
            reference_no: dto.reference_no,
            raw_payload: dto.raw_payload,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&GatewayTransaction> for GatewayTransactionResponseDto {
    fn from(entity: &GatewayTransaction) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            provider_id: entity.provider_id.clone(),
            provider_code: entity.provider_code.clone(),
            provider_transaction_id: entity.provider_transaction_id.clone(),
            direction: entity.direction.clone(),
            party_type: entity.party_type.clone(),
            party_id: entity.party_id.clone(),
            gross_amount: entity.gross_amount.clone(),
            fee_amount: entity.fee_amount.clone(),
            net_amount: entity.net_amount.clone(),
            currency: entity.currency.clone(),
            status: entity.status.clone(),
            posting_state: entity.posting_state.clone(),
            payment_entry_id: entity.payment_entry_id.clone(),
            fee_post_id: entity.fee_post_id.clone(),
            settled_at: entity.settled_at.clone(),
            reference_no: entity.reference_no.clone(),
            raw_payload: entity.raw_payload.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateGatewayTransactionDto> for GatewayTransaction {
    fn from_create_dto(dto: CreateGatewayTransactionDto) -> backbone_core::ServiceResult<Self> {
        Ok(GatewayTransaction::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateGatewayTransactionDto> for GatewayTransaction {
    fn apply_update(mut self, dto: UpdateGatewayTransactionDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.provider_id = dto.provider_id;
        self.provider_code = dto.provider_code;
        self.provider_transaction_id = dto.provider_transaction_id;
        self.direction = dto.direction;
        self.party_type = dto.party_type;
        self.party_id = dto.party_id;
        self.gross_amount = dto.gross_amount;
        self.fee_amount = dto.fee_amount;
        self.net_amount = dto.net_amount;
        self.currency = dto.currency;
        self.status = dto.status;
        self.posting_state = dto.posting_state;
        self.payment_entry_id = dto.payment_entry_id;
        self.fee_post_id = dto.fee_post_id;
        self.settled_at = dto.settled_at;
        self.reference_no = dto.reference_no;
        self.raw_payload = dto.raw_payload;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to GatewayTransaction here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
