//! PaymentGatewayProvider DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PaymentGatewayProvider;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::GatewayProviderCode;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PaymentGatewayProvider
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePaymentGatewayProviderDto {
    pub code: GatewayProviderCode,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "display_name")]
    pub display_name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "credentials_ref")]
    pub credentials_ref: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "fee_account_id")]
    pub fee_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "settlement_account_id")]
    pub settlement_account_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PaymentGatewayProvider
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePaymentGatewayProviderDto {
    pub code: GatewayProviderCode,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "display_name")]
    pub display_name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "credentials_ref")]
    pub credentials_ref: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "fee_account_id")]
    pub fee_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "settlement_account_id")]
    pub settlement_account_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PaymentGatewayProvider
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPaymentGatewayProviderDto {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<GatewayProviderCode>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "display_name")]
    pub display_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "credentials_ref")]
    pub credentials_ref: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "fee_account_id")]
    pub fee_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "settlement_account_id")]
    pub settlement_account_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_active")]
    pub is_active: Option<bool>,
}

impl PatchPaymentGatewayProviderDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.code.is_some() || self.company_id.is_some() || self.display_name.is_some() || self.credentials_ref.is_some() || self.fee_account_id.is_some() || self.settlement_account_id.is_some() || self.is_active.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PaymentGatewayProvider entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PaymentGatewayProviderResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    pub code: GatewayProviderCode,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub display_name: String,
    pub credentials_ref: Option<String>,
    pub fee_account_id: Option<Uuid>,
    pub settlement_account_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PaymentGatewayProvider entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PaymentGatewayProviderListResponseDto {
    /// List of items
    pub items: Vec<PaymentGatewayProviderResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PaymentGatewayProviderListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PaymentGatewayProviderResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PaymentGatewayProviderSummaryDto {
    pub id: Uuid,
    pub code: GatewayProviderCode,
    pub company_id: Uuid,
    pub display_name: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PaymentGatewayProvider> for PaymentGatewayProviderResponseDto {
    fn from(entity: PaymentGatewayProvider) -> Self {
        Self {
            id: entity.id,
            code: entity.code,
            company_id: entity.company_id,
            display_name: entity.display_name,
            credentials_ref: entity.credentials_ref,
            fee_account_id: entity.fee_account_id,
            settlement_account_id: entity.settlement_account_id,
            is_active: entity.is_active,
            metadata: entity.metadata,
        }
    }
}

impl From<PaymentGatewayProvider> for PaymentGatewayProviderSummaryDto {
    fn from(entity: PaymentGatewayProvider) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            code: entity.code,
            company_id: entity.company_id,
            display_name: entity.display_name,
            created_at,
        }
    }
}

impl From<CreatePaymentGatewayProviderDto> for PaymentGatewayProvider {
    fn from(dto: CreatePaymentGatewayProviderDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            code: dto.code,
            company_id: dto.company_id,
            display_name: dto.display_name,
            credentials_ref: dto.credentials_ref,
            fee_account_id: dto.fee_account_id,
            settlement_account_id: dto.settlement_account_id,
            is_active: dto.is_active,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PaymentGatewayProvider> for PaymentGatewayProviderResponseDto {
    fn from(entity: &PaymentGatewayProvider) -> Self {
        Self {
            id: entity.id.clone(),
            code: entity.code.clone(),
            company_id: entity.company_id.clone(),
            display_name: entity.display_name.clone(),
            credentials_ref: entity.credentials_ref.clone(),
            fee_account_id: entity.fee_account_id.clone(),
            settlement_account_id: entity.settlement_account_id.clone(),
            is_active: entity.is_active.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePaymentGatewayProviderDto> for PaymentGatewayProvider {
    fn from_create_dto(dto: CreatePaymentGatewayProviderDto) -> backbone_core::ServiceResult<Self> {
        Ok(PaymentGatewayProvider::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePaymentGatewayProviderDto> for PaymentGatewayProvider {
    fn apply_update(mut self, dto: UpdatePaymentGatewayProviderDto) -> backbone_core::ServiceResult<Self> {
        self.code = dto.code;
        self.company_id = dto.company_id;
        self.display_name = dto.display_name;
        self.credentials_ref = dto.credentials_ref;
        self.fee_account_id = dto.fee_account_id;
        self.settlement_account_id = dto.settlement_account_id;
        self.is_active = dto.is_active;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PaymentGatewayProvider here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
