//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod gateway_transaction_specification;
pub mod payment_gateway_provider_specification;

// <<< CUSTOM
// END CUSTOM
