//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{AndSpecification, NotSpecification, OrSpecification, Specification};

pub mod gateway_transaction_specification;
pub mod payment_gateway_provider_specification;

// <<< CUSTOM
// END CUSTOM
