//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod gateway_transaction_domain_policy;
pub mod payment_gateway_provider_domain_policy;

pub use gateway_transaction_domain_policy::GatewayTransactionDomainPolicy;
pub use payment_gateway_provider_domain_policy::PaymentGatewayProviderDomainPolicy;

// <<< CUSTOM
// END CUSTOM
