//! Domain policy for PaymentGatewayProvider aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::PaymentGatewayProvider;

/// Domain policy for PaymentGatewayProvider — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<PaymentGatewayProvider>` in the `// <<< CUSTOM` zone.
pub type PaymentGatewayProviderDomainPolicy = PermitAllPolicy<PaymentGatewayProvider>;

// <<< CUSTOM
// END CUSTOM
