//! Application service for GatewayTransaction entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `gateway_transaction_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateGatewayTransactionDto, UpdateGatewayTransactionDto};
use crate::domain::entity::GatewayTransaction;
use crate::infrastructure::persistence::GatewayTransactionRepository;

/// Application service for GatewayTransaction entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `gateway_transaction_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct GatewayTransactionServiceCustom {
///     inner: Arc<GatewayTransactionService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type GatewayTransactionService = GenericCrudService<
    GatewayTransaction,
    CreateGatewayTransactionDto,
    UpdateGatewayTransactionDto,
    GatewayTransactionRepository,
>;

// <<< CUSTOM
// END CUSTOM
