//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod gateway_transaction_service;
pub mod payment_gateway_provider_service;

// <<< CUSTOM
pub mod gateway_gl;
pub mod gateway_events;
pub mod gateway_provider;
pub mod gateway_write_service;
// END CUSTOM

pub use gateway_transaction_service::GatewayTransactionService;
pub use payment_gateway_provider_service::PaymentGatewayProviderService;
// <<< CUSTOM
pub use gateway_events::{
    GatewayEvent, GatewayEventSink, GatewayTransactionRefunded, GatewayTransactionSettled,
    LoggingGatewaySink,
};
pub use gateway_gl::{
    AccountingPostEnvelope, GlPostSink, GlPostAck, GlPostLine, GlPostRejected,
};
pub use gateway_provider::{
    ChargeCreated, CreateChargeRequest, GatewayError as ProviderError, GatewayTxStatus,
    ManualGatewayProvider, PaymentGatewayProvider, PaymentGatewayRegistry, RefundResult,
    StubGatewayProvider,
};
pub use gateway_write_service::{GatewayError, GatewayWriteService, SettleOutcome};
// END CUSTOM