-- GatewayTransaction Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the payment_gateway.gateway_transactions table.
-- Customize this file to add your initial data.

-- INSERT INTO payment_gateway.gateway_transactions (
--     id,
--     company_id,
--     provider_id,
--     provider_code,
--     provider_transaction_id,
--     direction,
--     party_type,
--     party_id,
--     gross_amount,
--     fee_amount,
--     net_amount,
--     currency,
--     status,
--     posting_state,
--     payment_entry_id,
--     fee_post_id,
--     settled_at,
--     reference_no,
--     raw_payload,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO payment_gateway.gateway_transactions (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

