-- PaymentGatewayProvider Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the payment_gateway.payment_gateway_providers table.
-- Customize this file to add your initial data.

-- INSERT INTO payment_gateway.payment_gateway_providers (
--     id,
--     code,
--     company_id,
--     display_name,
--     credentials_ref,
--     fee_account_id,
--     settlement_account_id,
--     is_active,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO payment_gateway.payment_gateway_providers (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

