-- Migration: Create gateway_transactions table
-- Generated by metaphor-schema

-- Create gateway_provider_code enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gateway_provider_code') THEN
        CREATE TYPE gateway_provider_code AS ENUM ('manual', 'midtrans', 'xendit', 'doku', 'stripe');
    END IF;
END
$$;

-- Create gateway_direction enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gateway_direction') THEN
        CREATE TYPE gateway_direction AS ENUM ('receive', 'pay');
    END IF;
END
$$;

-- Create gateway_party_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gateway_party_type') THEN
        CREATE TYPE gateway_party_type AS ENUM ('customer', 'supplier', 'employee');
    END IF;
END
$$;

-- Create gateway_transaction_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gateway_transaction_status') THEN
        CREATE TYPE gateway_transaction_status AS ENUM ('pending', 'authorized', 'captured', 'settled', 'refunded', 'failed');
    END IF;
END
$$;

-- Create gateway_posting_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gateway_posting_state') THEN
        CREATE TYPE gateway_posting_state AS ENUM ('pending', 'posted', 'failed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS payment_gateway;

CREATE TABLE IF NOT EXISTS payment_gateway.gateway_transactions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    provider_id UUID NOT NULL,
    provider_code gateway_provider_code NOT NULL,
    provider_transaction_id TEXT NOT NULL,
    direction gateway_direction NOT NULL DEFAULT 'receive',
    party_type gateway_party_type,
    party_id UUID,
    gross_amount NUMERIC(18, 2) NOT NULL CHECK (gross_amount >= 0),
    fee_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (fee_amount >= 0),
    net_amount NUMERIC(18, 2) NOT NULL CHECK (net_amount >= 0),
    currency TEXT NOT NULL DEFAULT 'IDR',
    status gateway_transaction_status NOT NULL DEFAULT 'pending',
    posting_state gateway_posting_state NOT NULL DEFAULT 'pending',
    payment_entry_id UUID,
    fee_post_id UUID,
    settled_at TIMESTAMPTZ,
    reference_no TEXT,
    raw_payload JSONB,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_gateway_transactions_provider_code_provider_transaction_id ON payment_gateway.gateway_transactions (provider_code, provider_transaction_id) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_gateway_transactions_company_id_status ON payment_gateway.gateway_transactions (company_id, status);

CREATE INDEX IF NOT EXISTS idx_gateway_transactions_payment_entry_id ON payment_gateway.gateway_transactions (payment_entry_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_gateway_transactions_metadata_gin ON payment_gateway.gateway_transactions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_gateway_transactions_metadata_deleted_at ON payment_gateway.gateway_transactions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_gateway_transactions_metadata_created_at ON payment_gateway.gateway_transactions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_gateway_transactions_metadata_updated_at ON payment_gateway.gateway_transactions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION payment_gateway.gateway_transactions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS gateway_transactions_insert_audit ON payment_gateway.gateway_transactions;
CREATE TRIGGER gateway_transactions_insert_audit BEFORE INSERT ON payment_gateway.gateway_transactions
    FOR EACH ROW EXECUTE FUNCTION payment_gateway.gateway_transactions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS gateway_transactions_update_audit ON payment_gateway.gateway_transactions;
CREATE TRIGGER gateway_transactions_update_audit BEFORE UPDATE ON payment_gateway.gateway_transactions
    FOR EACH ROW EXECUTE FUNCTION payment_gateway.gateway_transactions_audit_timestamp();
