-- Enum types for payment-gateway module
-- Generated by metaphor-schema

-- Create gateway_direction enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gateway_direction') THEN
        CREATE TYPE gateway_direction AS ENUM ('receive', 'pay');
    END IF;
END
$$;

-- Create gateway_party_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gateway_party_type') THEN
        CREATE TYPE gateway_party_type AS ENUM ('customer', 'supplier', 'employee');
    END IF;
END
$$;

-- Create gateway_transaction_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gateway_transaction_status') THEN
        CREATE TYPE gateway_transaction_status AS ENUM ('pending', 'authorized', 'captured', 'settled', 'refunded', 'failed');
    END IF;
END
$$;

-- Create gateway_posting_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gateway_posting_state') THEN
        CREATE TYPE gateway_posting_state AS ENUM ('pending', 'posted', 'failed');
    END IF;
END
$$;

-- Create gateway_provider_code enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gateway_provider_code') THEN
        CREATE TYPE gateway_provider_code AS ENUM ('manual', 'midtrans', 'xendit', 'doku', 'stripe');
    END IF;
END
$$;

