-- Company RLS fence for payment-gateway module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for payment_gateway.gateway_transactions
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payment_gateway.gateway_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_gateway.gateway_transactions FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS gateway_transactions_company_isolation ON payment_gateway.gateway_transactions;
CREATE POLICY gateway_transactions_company_isolation ON payment_gateway.gateway_transactions
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for payment_gateway.payment_gateway_providers
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payment_gateway.payment_gateway_providers ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_gateway.payment_gateway_providers FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS payment_gateway_providers_company_isolation ON payment_gateway.payment_gateway_providers;
CREATE POLICY payment_gateway_providers_company_isolation ON payment_gateway.payment_gateway_providers
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

