-- Migration: Create payment_gateway_providers table
-- Generated by metaphor-schema

-- Create gateway_provider_code enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gateway_provider_code') THEN
        CREATE TYPE gateway_provider_code AS ENUM ('manual', 'midtrans', 'xendit', 'doku', 'stripe');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS payment_gateway;

CREATE TABLE IF NOT EXISTS payment_gateway.payment_gateway_providers (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    code gateway_provider_code NOT NULL,
    company_id UUID NOT NULL,
    display_name TEXT NOT NULL,
    credentials_ref TEXT,
    fee_account_id UUID,
    settlement_account_id UUID,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_payment_gateway_providers_company_id_code ON payment_gateway.payment_gateway_providers (company_id, code) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_payment_gateway_providers_code_is_active ON payment_gateway.payment_gateway_providers (code, is_active);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_payment_gateway_providers_metadata_gin ON payment_gateway.payment_gateway_providers USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_payment_gateway_providers_metadata_deleted_at ON payment_gateway.payment_gateway_providers ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_payment_gateway_providers_metadata_created_at ON payment_gateway.payment_gateway_providers ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_payment_gateway_providers_metadata_updated_at ON payment_gateway.payment_gateway_providers ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION payment_gateway.payment_gateway_providers_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS payment_gateway_providers_insert_audit ON payment_gateway.payment_gateway_providers;
CREATE TRIGGER payment_gateway_providers_insert_audit BEFORE INSERT ON payment_gateway.payment_gateway_providers
    FOR EACH ROW EXECUTE FUNCTION payment_gateway.payment_gateway_providers_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS payment_gateway_providers_update_audit ON payment_gateway.payment_gateway_providers;
CREATE TRIGGER payment_gateway_providers_update_audit BEFORE UPDATE ON payment_gateway.payment_gateway_providers
    FOR EACH ROW EXECUTE FUNCTION payment_gateway.payment_gateway_providers_audit_timestamp();
