-- Company fence posture for payment-gateway module (ADR-0014: strict)
-- Every company-scoped entity here carries company_id and is fenced strict: a session
-- sees only rows whose company_id equals the request-scoped company
-- (`set_config('app.company_id', <uuid>, true)`); an unset var sees zero rows
-- (fail-closed). The tables below were fenced by the ADR-0008-era RLS migrations with
-- this same predicate and policy names; this migration declares the posture (ADR-0014)
-- and re-states each policy verbatim — an idempotent refresh, not a semantic change.
-- Tables without company_id (global reference masters, parent-scoped children) are
-- implicitly outside the declaration and keep their existing posture.
-- Requires the app to connect as a non-superuser role; migrations/seeders run as
-- the owner and bypass.

-- Migration: company row-level-security fence for payment_gateway.gateway_transactions
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payment_gateway.gateway_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_gateway.gateway_transactions FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS gateway_transactions_company_isolation ON payment_gateway.gateway_transactions;
CREATE POLICY gateway_transactions_company_isolation ON payment_gateway.gateway_transactions
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for payment_gateway.payment_gateway_providers
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payment_gateway.payment_gateway_providers ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_gateway.payment_gateway_providers FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS payment_gateway_providers_company_isolation ON payment_gateway.payment_gateway_providers;
CREATE POLICY payment_gateway_providers_company_isolation ON payment_gateway.payment_gateway_providers
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

