//! Domain events for GatewayTransaction entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::GatewayTransaction;

/// Domain events for GatewayTransaction — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<GatewayTransaction>)` variant.
pub type GatewayTransactionEvent = CrudEvent<GatewayTransaction>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for GatewayTransaction events.
pub type GatewayTransactionEventPublisher = Arc<dyn CrudEventPublisher<GatewayTransaction> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopGatewayTransactionEventPublisher = NoOpCrudEventPublisher<GatewayTransaction>;
