//! Event handler trait for GatewayTransaction events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::GatewayTransactionEvent;

/// Event handler for GatewayTransaction events.
/// Implement this trait to react to GatewayTransaction lifecycle events.
pub trait GatewayTransactionEventHandler: EventHandler<GatewayTransactionEvent> {}
