//! Domain events for PaymentGatewayProvider entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PaymentGatewayProvider;

/// Domain events for PaymentGatewayProvider — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PaymentGatewayProvider>)` variant.
pub type PaymentGatewayProviderEvent = CrudEvent<PaymentGatewayProvider>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PaymentGatewayProvider events.
pub type PaymentGatewayProviderEventPublisher = Arc<dyn CrudEventPublisher<PaymentGatewayProvider> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPaymentGatewayProviderEventPublisher = NoOpCrudEventPublisher<PaymentGatewayProvider>;
