//! Event handler trait for PaymentGatewayProvider events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PaymentGatewayProviderEvent;

/// Event handler for PaymentGatewayProvider events.
/// Implement this trait to react to PaymentGatewayProvider lifecycle events.
pub trait PaymentGatewayProviderEventHandler: EventHandler<PaymentGatewayProviderEvent> {}
