//! Event subscriber type aliases for PaymentGateway module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::GatewayTransactionEvent;
use crate::domain::event::PaymentGatewayProviderEvent;

/// Subscriber for GatewayTransaction events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type GatewayTransactionEventSubscriber = GenericEventSubscriber<GatewayTransactionEvent>;

/// Subscriber for PaymentGatewayProvider events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PaymentGatewayProviderEventSubscriber = GenericEventSubscriber<PaymentGatewayProviderEvent>;

// <<< CUSTOM
// END CUSTOM
