//! GatewayTransaction seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial GatewayTransaction data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// GATEWAYTRANSACTION SEEDER
// ============================================================================

/// Seeder for gateway_transaction
pub struct SeedGatewayTransactionSeeder;

impl SeedGatewayTransactionSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedGatewayTransactionSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedGatewayTransactionSeeder {
    fn name(&self) -> &'static str {
        "SeedGatewayTransactionSeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if payment_gateway.gateway_transactions table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM payment_gateway.gateway_transactions")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/gateway_transaction_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM payment_gateway.gateway_transactions")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

