//! PaymentGatewayProvider seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial PaymentGatewayProvider data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// PAYMENTGATEWAYPROVIDER SEEDER
// ============================================================================

/// Seeder for payment_gateway_provider
pub struct SeedPaymentGatewayProviderSeeder;

impl SeedPaymentGatewayProviderSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedPaymentGatewayProviderSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedPaymentGatewayProviderSeeder {
    fn name(&self) -> &'static str {
        "SeedPaymentGatewayProviderSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if payment_gateway.payment_gateway_providers table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM payment_gateway.payment_gateway_providers")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/payment_gateway_provider_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM payment_gateway.payment_gateway_providers")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

