//! Repository trait for GatewayTransaction aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the GatewayTransaction aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{GatewayTransaction, GatewayDirection, GatewayPartyType, GatewayPostingState, GatewayProviderCode, GatewayTransactionStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct GatewayTransactionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl GatewayTransactionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct GatewayTransactionPaginatedResult {
    pub data: Vec<GatewayTransaction>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct GatewayTransactionFilter {
    pub company_id: Option<Uuid>,
    pub provider_id: Option<Uuid>,
    pub provider_code: Option<GatewayProviderCode>,
    pub provider_transaction_id: Option<String>,
    pub direction: Option<GatewayDirection>,
    pub party_type: Option<GatewayPartyType>,
    pub party_id: Option<Uuid>,
    pub currency: Option<String>,
    pub status: Option<GatewayTransactionStatus>,
    pub posting_state: Option<GatewayPostingState>,
    pub payment_entry_id: Option<Uuid>,
    pub fee_post_id: Option<Uuid>,
    pub reference_no: Option<String>,
}

impl GatewayTransactionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.provider_id.is_some() || self.provider_code.is_some() || self.provider_transaction_id.is_some() || self.direction.is_some() || self.party_type.is_some() || self.party_id.is_some() || self.currency.is_some() || self.status.is_some() || self.posting_state.is_some() || self.payment_entry_id.is_some() || self.fee_post_id.is_some() || self.reference_no.is_some()
    }
}

/// Repository trait for GatewayTransaction aggregate
///
/// This trait defines the persistence contract for GatewayTransaction entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait GatewayTransactionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new gateway_transaction entity
    async fn save(&self, entity: &GatewayTransaction) -> Result<GatewayTransaction>;

    /// Find gateway_transaction by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<GatewayTransaction>>;

    /// Find all gateway_transaction entities
    async fn find_all(&self) -> Result<Vec<GatewayTransaction>>;

    /// Update gateway_transaction by ID
    async fn update(&self, id: &str, entity: &GatewayTransaction) -> Result<Option<GatewayTransaction>>;

    /// Delete gateway_transaction by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List gateway_transaction with pagination
    async fn list(&self, params: GatewayTransactionPaginationParams) -> Result<GatewayTransactionPaginatedResult>;

    /// List gateway_transaction with pagination and filters
    async fn list_with_filters(&self, params: GatewayTransactionPaginationParams, filters: GatewayTransactionFilter) -> Result<GatewayTransactionPaginatedResult>;

    /// Count all gateway_transaction entities
    async fn count(&self) -> Result<u64>;

    /// Count gateway_transaction entities matching filters
    async fn count_with_filters(&self, filters: GatewayTransactionFilter) -> Result<u64>;

    /// Check if gateway_transaction exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete gateway_transaction by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted gateway_transaction by ID
    async fn restore(&self, id: &str) -> Result<Option<GatewayTransaction>>;

    /// List soft-deleted gateway_transaction entities
    async fn list_deleted(&self, params: GatewayTransactionPaginationParams) -> Result<GatewayTransactionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save gateway_transaction entities
    async fn bulk_save(&self, entities: &[GatewayTransaction]) -> Result<Vec<GatewayTransaction>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
