//! Repository trait for PaymentGatewayProvider aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PaymentGatewayProvider aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{PaymentGatewayProvider, GatewayProviderCode};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PaymentGatewayProviderPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PaymentGatewayProviderPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PaymentGatewayProviderPaginatedResult {
    pub data: Vec<PaymentGatewayProvider>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PaymentGatewayProviderFilter {
    pub code: Option<GatewayProviderCode>,
    pub company_id: Option<Uuid>,
    pub display_name: Option<String>,
    pub credentials_ref: Option<String>,
    pub fee_account_id: Option<Uuid>,
    pub settlement_account_id: Option<Uuid>,
    pub is_active: Option<bool>,
}

impl PaymentGatewayProviderFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.code.is_some() || self.company_id.is_some() || self.display_name.is_some() || self.credentials_ref.is_some() || self.fee_account_id.is_some() || self.settlement_account_id.is_some() || self.is_active.is_some()
    }
}

/// Repository trait for PaymentGatewayProvider aggregate
///
/// This trait defines the persistence contract for PaymentGatewayProvider entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PaymentGatewayProviderRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new payment_gateway_provider entity
    async fn save(&self, entity: &PaymentGatewayProvider) -> Result<PaymentGatewayProvider>;

    /// Find payment_gateway_provider by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PaymentGatewayProvider>>;

    /// Find all payment_gateway_provider entities
    async fn find_all(&self) -> Result<Vec<PaymentGatewayProvider>>;

    /// Update payment_gateway_provider by ID
    async fn update(&self, id: &str, entity: &PaymentGatewayProvider) -> Result<Option<PaymentGatewayProvider>>;

    /// Delete payment_gateway_provider by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List payment_gateway_provider with pagination
    async fn list(&self, params: PaymentGatewayProviderPaginationParams) -> Result<PaymentGatewayProviderPaginatedResult>;

    /// List payment_gateway_provider with pagination and filters
    async fn list_with_filters(&self, params: PaymentGatewayProviderPaginationParams, filters: PaymentGatewayProviderFilter) -> Result<PaymentGatewayProviderPaginatedResult>;

    /// Count all payment_gateway_provider entities
    async fn count(&self) -> Result<u64>;

    /// Count payment_gateway_provider entities matching filters
    async fn count_with_filters(&self, filters: PaymentGatewayProviderFilter) -> Result<u64>;

    /// Check if payment_gateway_provider exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete payment_gateway_provider by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted payment_gateway_provider by ID
    async fn restore(&self, id: &str) -> Result<Option<PaymentGatewayProvider>>;

    /// List soft-deleted payment_gateway_provider entities
    async fn list_deleted(&self, params: PaymentGatewayProviderPaginationParams) -> Result<PaymentGatewayProviderPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save payment_gateway_provider entities
    async fn bulk_save(&self, entities: &[PaymentGatewayProvider]) -> Result<Vec<PaymentGatewayProvider>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
