//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod gateway_transaction_repository;
mod payment_gateway_provider_repository;

// Custom persistence modules
// <<< CUSTOM
mod gateway_transaction_repository_custom;
// END CUSTOM

// Re-exports
pub use gateway_transaction_repository::GatewayTransactionRepository;
pub use payment_gateway_provider_repository::PaymentGatewayProviderRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
pub use gateway_transaction_repository_custom::{
    compose_fee_post, FeeSourceRow, SettledHeaderRow,
};
// END CUSTOM