//! Repository for PaymentGatewayProvider entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PaymentGatewayProvider, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PaymentGatewayProvider;

/// Table name for PaymentGatewayProvider entities
pub const TABLE_NAME: &str = "payment_gateway.payment_gateway_providers";

/// Repository for PaymentGatewayProvider entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PaymentGatewayProviderRepository(
    backbone_orm::GenericCrudRepository<PaymentGatewayProvider, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PaymentGatewayProviderRepository {
    type Target = backbone_orm::GenericCrudRepository<PaymentGatewayProvider, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PaymentGatewayProviderRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PaymentGatewayProviderRepository, PaymentGatewayProvider, soft_delete);
