//! Validator for GatewayTransaction entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<GatewayTransaction>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use crate::domain::entity::GatewayTransaction;
use backbone_core::{EntityValidator, ValidationError, ValidationErrors};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};

/// Validator type alias for GatewayTransaction entities.
pub type GatewayTransactionValidator = EntityValidator<GatewayTransaction>;

/// Build a validator for GatewayTransaction with all schema-defined field rules.
pub fn gateway_transaction_validator() -> GatewayTransactionValidator {
    EntityValidator::new()
        .rule(RequiredString::new(
            "provider_transaction_id",
            |e: &GatewayTransaction| &e.provider_transaction_id,
        ))
        .rule(RequiredString::new("currency", |e: &GatewayTransaction| {
            &e.currency
        }))
        .rule(OptionalNotBlank::new(
            "reference_no",
            |e: &GatewayTransaction| e.reference_no.as_deref(),
        ))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
