//! Validator for PaymentGatewayProvider entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PaymentGatewayProvider>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::PaymentGatewayProvider;

/// Validator type alias for PaymentGatewayProvider entities.
pub type PaymentGatewayProviderValidator = EntityValidator<PaymentGatewayProvider>;

/// Build a validator for PaymentGatewayProvider with all schema-defined field rules.
pub fn payment_gateway_provider_validator() -> PaymentGatewayProviderValidator {
    EntityValidator::new()
        .rule(RequiredString::new("display_name", |e: &PaymentGatewayProvider| &e.display_name))
        .rule(OptionalNotBlank::new("credentials_ref", |e: &PaymentGatewayProvider| e.credentials_ref.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
