//! Auth configuration for GatewayTransaction handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<GatewayTransaction>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::GatewayTransactionService;
use crate::domain::entity::GatewayTransaction;

/// Permission string constants for GatewayTransaction operations.
pub mod permissions {
    pub const LIST:        &str = "gateway_transaction:list";
    pub const READ:        &str = "gateway_transaction:read";
    pub const CREATE:      &str = "gateway_transaction:create";
    pub const UPDATE:      &str = "gateway_transaction:update";
    pub const DELETE:      &str = "gateway_transaction:delete";
    pub const RESTORE:     &str = "gateway_transaction:restore";
    pub const TRASH:       &str = "gateway_transaction:trash";
    pub const EMPTY_TRASH: &str = "gateway_transaction:empty_trash";
    pub const BULK_CREATE: &str = "gateway_transaction:bulk_create";
    pub const UPSERT:      &str = "gateway_transaction:upsert";
}

/// Resource policy for GatewayTransaction — maps CRUD actions to permission strings.
pub struct GatewayTransactionPolicy;

#[async_trait]
impl ResourcePolicy<GatewayTransaction> for GatewayTransactionPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &GatewayTransaction,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for GatewayTransaction handlers.
///
/// Wraps `GatewayTransactionService` and checks `GatewayTransactionPolicy` before delegating.
pub type GatewayTransactionGuard = PermissionGuard<GatewayTransaction>;

/// Service-integrated permission guard for GatewayTransaction (for use in generated handlers).
pub type GatewayTransactionServiceGuard = ServicePermissionGuard<GatewayTransaction, GatewayTransactionService, GatewayTransactionPolicy>;

// <<< CUSTOM
// END CUSTOM
