//! Auth configuration for PaymentGatewayProvider handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<PaymentGatewayProvider>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PaymentGatewayProviderService;
use crate::domain::entity::PaymentGatewayProvider;

/// Permission string constants for PaymentGatewayProvider operations.
pub mod permissions {
    pub const LIST:        &str = "payment_gateway_provider:list";
    pub const READ:        &str = "payment_gateway_provider:read";
    pub const CREATE:      &str = "payment_gateway_provider:create";
    pub const UPDATE:      &str = "payment_gateway_provider:update";
    pub const DELETE:      &str = "payment_gateway_provider:delete";
    pub const RESTORE:     &str = "payment_gateway_provider:restore";
    pub const TRASH:       &str = "payment_gateway_provider:trash";
    pub const EMPTY_TRASH: &str = "payment_gateway_provider:empty_trash";
    pub const BULK_CREATE: &str = "payment_gateway_provider:bulk_create";
    pub const UPSERT:      &str = "payment_gateway_provider:upsert";
}

/// Resource policy for PaymentGatewayProvider — maps CRUD actions to permission strings.
pub struct PaymentGatewayProviderPolicy;

#[async_trait]
impl ResourcePolicy<PaymentGatewayProvider> for PaymentGatewayProviderPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &PaymentGatewayProvider,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for PaymentGatewayProvider handlers.
///
/// Wraps `PaymentGatewayProviderService` and checks `PaymentGatewayProviderPolicy` before delegating.
pub type PaymentGatewayProviderGuard = PermissionGuard<PaymentGatewayProvider>;

/// Service-integrated permission guard for PaymentGatewayProvider (for use in generated handlers).
pub type PaymentGatewayProviderServiceGuard = ServicePermissionGuard<PaymentGatewayProvider, PaymentGatewayProviderService, PaymentGatewayProviderPolicy>;

// <<< CUSTOM
// END CUSTOM
