//! GatewayTransaction API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the GatewayTransaction CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// GATEWAYTRANSACTION TEST DATA GENERATOR
// ============================================================================

/// Test data generator for GatewayTransaction
pub struct GatewayTransactionTestData;

impl TestDataGenerator for GatewayTransactionTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "provider_id": Uuid::new_v4().to_string(),
            "provider_code": "manual",
            "provider_transaction_id": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "direction": "receive",
            "party_type": null,
            "party_id": null,
            "gross_amount": 0,
            "fee_amount": 0,
            "net_amount": 0,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "status": "pending",
            "posting_state": "pending",
            "payment_entry_id": null,
            "fee_post_id": null,
            "settled_at": now,
            "reference_no": null,
            "raw_payload": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "provider_id": Uuid::new_v4().to_string(),
            "provider_code": "manual",
            "provider_transaction_id": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "direction": "receive",
            "party_type": null,
            "party_id": null,
            "gross_amount": 0,
            "fee_amount": 0,
            "net_amount": 0,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "status": "pending",
            "posting_state": "pending",
            "payment_entry_id": null,
            "fee_post_id": null,
            "settled_at": now,
            "reference_no": null,
            "raw_payload": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/payment_gateway_providers", &super::payment_gateway_provider_api_test::PaymentGatewayProviderTestData).await {
            deps.push(("provider_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// GATEWAYTRANSACTION API TEST
// ============================================================================

/// GatewayTransaction API test suite
pub struct GatewayTransactionApiTest {
    inner: GenericCrudTest<GatewayTransactionTestData>,
}

impl GatewayTransactionApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/gateway_transactions", "GatewayTransaction");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, GatewayTransactionTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for GatewayTransactionApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_gateway_transaction_crud() {
        let mut test = GatewayTransactionApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add GatewayTransaction specific tests here
// <<< CUSTOM TESTS END >>>
