//! PaymentGatewayProvider API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the PaymentGatewayProvider CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// PAYMENTGATEWAYPROVIDER TEST DATA GENERATOR
// ============================================================================

/// Test data generator for PaymentGatewayProvider
pub struct PaymentGatewayProviderTestData;

impl TestDataGenerator for PaymentGatewayProviderTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "company_id": Uuid::new_v4().to_string(),
            "display_name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "credentials_ref": null,
            "fee_account_id": null,
            "settlement_account_id": null,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "company_id": Uuid::new_v4().to_string(),
            "display_name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "credentials_ref": null,
            "fee_account_id": null,
            "settlement_account_id": null,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// PAYMENTGATEWAYPROVIDER API TEST
// ============================================================================

/// PaymentGatewayProvider API test suite
pub struct PaymentGatewayProviderApiTest {
    inner: GenericCrudTest<PaymentGatewayProviderTestData>,
}

impl PaymentGatewayProviderApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/payment_gateway_providers", "PaymentGatewayProvider");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, PaymentGatewayProviderTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for PaymentGatewayProviderApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_payment_gateway_provider_crud() {
        let mut test = PaymentGatewayProviderApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add PaymentGatewayProvider specific tests here
// <<< CUSTOM TESTS END >>>
