//! PaymentGateway Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::GatewayTransactionService;
use crate::application::service::PaymentGatewayProviderService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// GatewayTransaction service
    pub gateway_transaction_service: Arc<GatewayTransactionService>,
    /// PaymentGatewayProvider service
    pub payment_gateway_provider_service: Arc<PaymentGatewayProviderService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        gateway_transaction_service: Arc<GatewayTransactionService>,
        payment_gateway_provider_service: Arc<PaymentGatewayProviderService>
    ) -> Self {
        Self {
            gateway_transaction_service,
            payment_gateway_provider_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::PaymentGatewayModule) -> Self {
        Self {
            gateway_transaction_service: module.gateway_transaction_service.clone(),
            payment_gateway_provider_service: module.payment_gateway_provider_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    gateway_transaction_service: Option<Arc<GatewayTransactionService>>,
    payment_gateway_provider_service: Option<Arc<PaymentGatewayProviderService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the GatewayTransaction service.
    pub fn with_gateway_transaction_service(mut self, service: Arc<GatewayTransactionService>) -> Self {
        self.gateway_transaction_service = Some(service);
        self
    }

    /// Set the PaymentGatewayProvider service.
    pub fn with_payment_gateway_provider_service(mut self, service: Arc<PaymentGatewayProviderService>) -> Self {
        self.payment_gateway_provider_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            gateway_transaction_service: self.gateway_transaction_service.expect("gateway_transaction_service is required"),
            payment_gateway_provider_service: self.payment_gateway_provider_service.expect("payment_gateway_provider_service is required"),
        }
    }
}
