//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    gateway_transaction_handler::create_gateway_transaction_routes,
    payment_gateway_provider_handler::create_payment_gateway_provider_routes,
};

use crate::application::service::{
    GatewayTransactionService,
    PaymentGatewayProviderService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub gateway_transaction: Arc<GatewayTransactionService>,
    pub payment_gateway_provider: Arc<PaymentGatewayProviderService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // GatewayTransaction routes (12 Backbone endpoints)
        .merge(create_gateway_transaction_routes(services.gateway_transaction))
        // PaymentGatewayProvider routes (12 Backbone endpoints)
        .merge(create_payment_gateway_provider_routes(services.payment_gateway_provider))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn gateway_transaction_routes(service: Arc<GatewayTransactionService>) -> Router {
        create_gateway_transaction_routes(service)
    }

    pub fn payment_gateway_provider_routes(service: Arc<PaymentGatewayProviderService>) -> Router {
        create_payment_gateway_provider_routes(service)
    }

}
