//! Public events for PaymentGateway module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// GATEWAYTRANSACTION EVENTS
// ============================================================================

/// Event published when a GatewayTransaction is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GatewayTransactionCreatedEvent {
    pub id: GatewayTransactionId,
    pub data: GatewayTransactionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a GatewayTransaction is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GatewayTransactionUpdatedEvent {
    pub id: GatewayTransactionId,
    pub data: GatewayTransactionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a GatewayTransaction is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GatewayTransactionDeletedEvent {
    pub id: GatewayTransactionId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PAYMENTGATEWAYPROVIDER EVENTS
// ============================================================================

/// Event published when a PaymentGatewayProvider is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentGatewayProviderCreatedEvent {
    pub id: PaymentGatewayProviderId,
    pub data: PaymentGatewayProviderDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PaymentGatewayProvider is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentGatewayProviderUpdatedEvent {
    pub id: PaymentGatewayProviderId,
    pub data: PaymentGatewayProviderDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PaymentGatewayProvider is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentGatewayProviderDeletedEvent {
    pub id: PaymentGatewayProviderId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by PaymentGateway module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PaymentGatewayEvent {
    GatewayTransactionCreated(GatewayTransactionCreatedEvent),
    GatewayTransactionUpdated(GatewayTransactionUpdatedEvent),
    GatewayTransactionDeleted(GatewayTransactionDeletedEvent),
    PaymentGatewayProviderCreated(PaymentGatewayProviderCreatedEvent),
    PaymentGatewayProviderUpdated(PaymentGatewayProviderUpdatedEvent),
    PaymentGatewayProviderDeleted(PaymentGatewayProviderDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentGatewayEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for PaymentGatewayEventMetadata {
    fn default() -> Self {
        Self {
            module: "payment-gateway",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
