//! PaymentGateway Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that PaymentGateway exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use payment-gateway::exports::{GatewayTransactionDto, PaymentGatewayQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `GatewayTransactionDto` - Data transfer object for GatewayTransaction
/// - `GatewayTransactionSummary` - Summary view of GatewayTransaction
/// - `GatewayTransactionId` - Type-safe ID wrapper
/// - `PaymentGatewayProviderDto` - Data transfer object for PaymentGatewayProvider
/// - `PaymentGatewayProviderSummary` - Summary view of PaymentGatewayProvider
/// - `PaymentGatewayProviderId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `PaymentGatewayQueryService` - Read-only queries
///
/// ## Public Events
/// - `GatewayTransactionCreatedEvent` - Published when GatewayTransaction is created
/// - `GatewayTransactionUpdatedEvent` - Published when GatewayTransaction is updated
/// - `GatewayTransactionDeletedEvent` - Published when GatewayTransaction is deleted
/// - `PaymentGatewayProviderCreatedEvent` - Published when PaymentGatewayProvider is created
/// - `PaymentGatewayProviderUpdatedEvent` - Published when PaymentGatewayProvider is updated
/// - `PaymentGatewayProviderDeletedEvent` - Published when PaymentGatewayProvider is deleted
pub struct ExportSummary;
