//! Public services for PaymentGateway module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for PaymentGateway module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait PaymentGatewayQueryService: Send + Sync {
    /// Get GatewayTransaction by ID
    async fn get_gateway_transaction(&self, id: GatewayTransactionId) -> Result<Option<GatewayTransactionDto>>;

    /// Get GatewayTransaction summary by ID
    async fn get_gateway_transaction_summary(&self, id: GatewayTransactionId) -> Result<Option<GatewayTransactionSummary>>;

    /// Check if GatewayTransaction exists
    async fn gateway_transaction_exists(&self, id: GatewayTransactionId) -> Result<bool>;

    /// Get PaymentGatewayProvider by ID
    async fn get_payment_gateway_provider(&self, id: PaymentGatewayProviderId) -> Result<Option<PaymentGatewayProviderDto>>;

    /// Get PaymentGatewayProvider summary by ID
    async fn get_payment_gateway_provider_summary(&self, id: PaymentGatewayProviderId) -> Result<Option<PaymentGatewayProviderSummary>>;

    /// Check if PaymentGatewayProvider exists
    async fn payment_gateway_provider_exists(&self, id: PaymentGatewayProviderId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of PaymentGatewayQueryService
pub struct PaymentGatewayQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> PaymentGatewayQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
