//! Public types for PaymentGateway module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// GATEWAYTRANSACTION TYPES
// ============================================================================

/// Type-safe ID for GatewayTransaction
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct GatewayTransactionId(pub Uuid);

impl GatewayTransactionId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for GatewayTransactionId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<GatewayTransactionId> for Uuid {
    fn from(id: GatewayTransactionId) -> Self {
        id.0
    }
}

/// Data transfer object for GatewayTransaction
///
/// This is the public representation of GatewayTransaction for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GatewayTransactionDto {
    pub id: GatewayTransactionId,
    pub company_id: Uuid,
    pub provider_id: Uuid,
    pub provider_code: GatewayProviderCode,
    pub provider_transaction_id: String,
    pub direction: GatewayDirection,
    pub party_type: Option<GatewayPartyType>,
    pub party_id: Option<Uuid>,
    pub gross_amount: Decimal,
    pub fee_amount: Decimal,
    pub net_amount: Decimal,
    pub currency: String,
    pub status: GatewayTransactionStatus,
    pub posting_state: GatewayPostingState,
    pub payment_entry_id: Option<Uuid>,
    pub fee_post_id: Option<Uuid>,
    pub settled_at: Option<DateTime<Utc>>,
    pub reference_no: Option<String>,
    pub raw_payload: Option<serde_json::Value>,
    pub metadata: serde_json::Value,
}

/// Summary view of GatewayTransaction for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GatewayTransactionSummary {
    pub id: GatewayTransactionId,
    pub status: GatewayTransactionStatus,
}

/// Reference to GatewayTransaction for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GatewayTransactionRef {
    pub id: GatewayTransactionId,
}

// ============================================================================
// PAYMENTGATEWAYPROVIDER TYPES
// ============================================================================

/// Type-safe ID for PaymentGatewayProvider
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PaymentGatewayProviderId(pub Uuid);

impl PaymentGatewayProviderId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PaymentGatewayProviderId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PaymentGatewayProviderId> for Uuid {
    fn from(id: PaymentGatewayProviderId) -> Self {
        id.0
    }
}

/// Data transfer object for PaymentGatewayProvider
///
/// This is the public representation of PaymentGatewayProvider for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentGatewayProviderDto {
    pub id: PaymentGatewayProviderId,
    pub code: GatewayProviderCode,
    pub company_id: Uuid,
    pub display_name: String,
    pub credentials_ref: Option<String>,
    pub fee_account_id: Option<Uuid>,
    pub settlement_account_id: Option<Uuid>,
    pub is_active: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of PaymentGatewayProvider for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentGatewayProviderSummary {
    pub id: PaymentGatewayProviderId,
    pub display_name: String,
}

/// Reference to PaymentGatewayProvider for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentGatewayProviderRef {
    pub id: PaymentGatewayProviderId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
