//! PaymentGateway Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::GatewayTransactionService;
pub use application::service::PaymentGatewayProviderService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// PaymentGateway module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let payment-gateway = PaymentGatewayModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = payment-gateway.all_crud_routes();
/// ```
pub struct PaymentGatewayModule {
    pub gateway_transaction_service: Arc<GatewayTransactionService>,
    pub payment_gateway_provider_service: Arc<PaymentGatewayProviderService>,
}

impl PaymentGatewayModule {
    /// Create a new module builder
    pub fn builder() -> PaymentGatewayModuleBuilder {
        PaymentGatewayModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_gateway_transaction_routes,
            create_payment_gateway_provider_routes,
        };

        Router::new()
            .merge(create_gateway_transaction_routes(self.gateway_transaction_service.clone()))
            .merge(create_payment_gateway_provider_routes(self.payment_gateway_provider_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for PaymentGatewayModule
pub struct PaymentGatewayModuleBuilder {
    db_pool: Option<PgPool>,
}

impl PaymentGatewayModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<PaymentGatewayModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // GatewayTransaction service
        let gateway_transaction_repository = Arc::new(GatewayTransactionRepository::new(db_pool.clone()));
        let gateway_transaction_service = Arc::new(GatewayTransactionService::with_repository(gateway_transaction_repository.clone()));

        // PaymentGatewayProvider service
        let payment_gateway_provider_repository = Arc::new(PaymentGatewayProviderRepository::new(db_pool.clone()));
        let payment_gateway_provider_service = Arc::new(PaymentGatewayProviderService::with_repository(payment_gateway_provider_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(PaymentGatewayModule {
            gateway_transaction_service,
            payment_gateway_provider_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for PaymentGatewayModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
