//! PaymentGateway Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::GatewayTransactionService;
pub use application::service::PaymentGatewayProviderService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

// <<< CUSTOM
#[cfg(feature = "codecs")]
use application::service::{
    CredentialReader, GatewayCodecRegistry, StatusRefetch, WebhookIngestService,
};
use application::service::{GatewayEventSink, GatewayWriteService, GlPostSink, LoggingGatewaySink};
use presentation::http::{create_gateway_webhook_routes, WebhookState};
// END CUSTOM

/// PaymentGateway module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let payment-gateway = PaymentGatewayModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = payment-gateway.all_crud_routes();
/// ```
pub struct PaymentGatewayModule {
    pub(crate) gateway_transaction_service: Arc<GatewayTransactionService>,
    pub(crate) payment_gateway_provider_service: Arc<PaymentGatewayProviderService>,
    // <<< CUSTOM FIELDS
    /// The settlement engine (settle + reverse). Exposed so composition can mount
    /// the webhook router or drive settlement directly.
    pub write_service: Arc<GatewayWriteService>,
    /// Composition-provided fee sink. `None` ⇒ `gateway_webhook_router()` returns
    /// `None` (the webhook cannot post the fee companion journal without one).
    pub fee_sink: Option<Arc<dyn GlPostSink>>,
    /// The verified webhook ingest pipeline, built when composition provided both
    /// I/O ports (credential reader + status re-fetcher) and a fee sink. `None`
    /// ⇒ the bare webhook routes cannot be mounted (they would have no way to
    /// verify or re-fetch — mounting them is refused, not degraded).
    #[cfg(feature = "codecs")]
    pub ingest_service: Option<Arc<WebhookIngestService>>,
    // END CUSTOM
}

impl PaymentGatewayModule {
    /// Create a new module builder
    pub fn builder() -> PaymentGatewayModuleBuilder {
        PaymentGatewayModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_gateway_transaction_routes,
            create_payment_gateway_provider_routes,
        };

        Router::new()
            .merge(create_gateway_transaction_routes(self.gateway_transaction_service.clone()))
            .merge(create_payment_gateway_provider_routes(self.payment_gateway_provider_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_gateway_transaction_read_routes,
            create_payment_gateway_provider_read_routes,
        };

        Router::new()
            .merge(create_gateway_transaction_read_routes(self.gateway_transaction_service.clone()))
            .merge(create_payment_gateway_provider_read_routes(self.payment_gateway_provider_service.clone()))
    }

    // <<< CUSTOM METHODS
    /// Build the gateway webhook router (`POST /webhook/settle`), if a fee sink
    /// was configured on the builder. Returns `None` when no fee sink was provided
    /// — the webhook cannot post the fee companion journal without one. The
    /// composition layer mounts this behind its own provider-specific signature
    /// verification.
    pub fn gateway_webhook_router(&self) -> Option<Router> {
        let fee_sink = self.fee_sink.clone()?;
        Some(create_gateway_webhook_routes(WebhookState {
            write_service: self.write_service.clone(),
            fee_sink,
        }))
    }

    /// The provider-config READ surface (GET endpoints on
    /// payment_gateway_providers). Compose with
    /// [`Self::provider_config_write_routes`] so a host can gate writes
    /// behind its own role check while reads ride tenant auth alone.
    pub fn provider_config_read_routes(&self) -> Router {
        use presentation::http::create_payment_gateway_provider_read_routes;
        create_payment_gateway_provider_read_routes(self.payment_gateway_provider_service.clone())
    }

    /// The provider-config WRITE surface (unguarded generic mutations on
    /// payment_gateway_providers). A host MUST wrap this in its own
    /// authorization before mounting — the generic CRUD carries no domain
    /// validation.
    pub fn provider_config_write_routes(&self) -> Router {
        use presentation::http::create_payment_gateway_provider_write_routes;
        create_payment_gateway_provider_write_routes(self.payment_gateway_provider_service.clone())
    }

    /// The gateway-transaction READ surface alone. Provider-fed rows are
    /// never operator-writable over HTTP — a host composes this as the
    /// transaction surface, never the generic writes.
    pub fn transaction_read_routes(&self) -> Router {
        use presentation::http::create_gateway_transaction_read_routes;
        create_gateway_transaction_read_routes(self.gateway_transaction_service.clone())
    }

    /// The verified ingest pipeline, when composition wired its ports. The bare
    /// webhook routes are only mountable through this — no pipeline, no route.
    #[cfg(feature = "codecs")]
    pub fn ingest_service(&self) -> Option<Arc<WebhookIngestService>> {
        self.ingest_service.clone()
    }
    // END CUSTOM
}

/// Builder for PaymentGatewayModule
pub struct PaymentGatewayModuleBuilder {
    db_pool: Option<PgPool>,
    // <<< CUSTOM
    fee_sink: Option<Arc<dyn GlPostSink>>,
    event_sink: Option<Arc<dyn GatewayEventSink>>,
    #[cfg(feature = "codecs")]
    credential_reader: Option<Arc<dyn CredentialReader>>,
    #[cfg(feature = "codecs")]
    refetcher: Option<Arc<dyn StatusRefetch>>,
    // END CUSTOM
}

impl PaymentGatewayModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
            // <<< CUSTOM
            fee_sink: None,
            event_sink: None,
            #[cfg(feature = "codecs")]
            credential_reader: None,
            #[cfg(feature = "codecs")]
            refetcher: None,
            // END CUSTOM
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    /// Provide the fee-post sink (composition's accounting client). Required for
    /// [`PaymentGatewayModule::gateway_webhook_router`] to return `Some`; without
    /// it the webhook cannot post the fee companion journal.
    pub fn with_fee_sink(mut self, sink: Arc<dyn GlPostSink>) -> Self {
        self.fee_sink = Some(sink);
        self
    }

    /// Provide the settlement-event sink (e.g. an outbox-backed bus). Defaults to
    /// [`LoggingGatewaySink`] (structured tracing) when not set — fine for tests
    /// and single-process setups; composition wires a durable bus for production.
    pub fn with_event_sink(mut self, sink: Arc<dyn GatewayEventSink>) -> Self {
        self.event_sink = Some(sink);
        self
    }

    /// Provide the credential-store read port (composition's adapter over the
    /// credential service). Required, together with [`Self::with_refetcher`]
    /// and a fee sink, for [`PaymentGatewayModule::ingest_service`] to exist.
    #[cfg(feature = "codecs")]
    pub fn with_credential_reader(mut self, reader: Arc<dyn CredentialReader>) -> Self {
        self.credential_reader = Some(reader);
        self
    }

    /// Provide the provider status re-fetch port (composition's API clients).
    /// Required, together with [`Self::with_credential_reader`] and a fee sink,
    /// for [`PaymentGatewayModule::ingest_service`] to exist.
    #[cfg(feature = "codecs")]
    pub fn with_refetcher(mut self, refetcher: Arc<dyn StatusRefetch>) -> Self {
        self.refetcher = Some(refetcher);
        self
    }
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<PaymentGatewayModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // GatewayTransaction service
        let gateway_transaction_repository = Arc::new(GatewayTransactionRepository::new(db_pool.clone()));
        let gateway_transaction_service = Arc::new(GatewayTransactionService::with_repository(gateway_transaction_repository.clone()));

        // PaymentGatewayProvider service
        let payment_gateway_provider_repository = Arc::new(PaymentGatewayProviderRepository::new(db_pool.clone()));
        let payment_gateway_provider_service = Arc::new(PaymentGatewayProviderService::with_repository(payment_gateway_provider_repository.clone()));

        // <<< CUSTOM
        // The settlement engine: defaults to a logging event sink when composition
        // hasn't wired a durable bus. The fee sink is held separately so the webhook
        // router is built iff composition provided one (gateway_webhook_router -> None otherwise).
        let event_sink: Arc<dyn GatewayEventSink> = self
            .event_sink
            .unwrap_or_else(|| Arc::new(LoggingGatewaySink));
        let write_service = Arc::new(GatewayWriteService::with_sink(db_pool.clone(), event_sink));
        let fee_sink = self.fee_sink;

        // The verified ingest pipeline exists only when composition wired BOTH
        // I/O ports (credential reader + re-fetcher) AND a fee sink — the bare
        // webhook routes are all-or-nothing, never mounted degraded.
        #[cfg(feature = "codecs")]
        let ingest_service = match (self.credential_reader, self.refetcher, fee_sink.clone()) {
            (Some(reader), Some(refetcher), Some(fee_sink)) => {
                Some(Arc::new(WebhookIngestService::new(
                    db_pool.clone(),
                    write_service.clone(),
                    GatewayCodecRegistry::with_builtin(),
                    reader,
                    refetcher,
                    fee_sink,
                )))
            }
            _ => None,
        };
        // END CUSTOM

        Ok(PaymentGatewayModule {
            gateway_transaction_service,
            payment_gateway_provider_service,
            // <<< CUSTOM
            write_service,
            fee_sink,
            #[cfg(feature = "codecs")]
            ingest_service,
            // END CUSTOM
        })
    }
}

impl Default for PaymentGatewayModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
