//! Use case type aliases for GatewayTransaction aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateGatewayTransactionDto, UpdateGatewayTransactionDto};
use crate::application::service::GatewayTransactionService;
use crate::domain::entity::GatewayTransaction;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateGatewayTransactionUseCase = CreateUseCase<GatewayTransaction, CreateGatewayTransactionDto, GatewayTransactionService>;
pub type UpdateGatewayTransactionUseCase = UpdateUseCase<GatewayTransaction, UpdateGatewayTransactionDto, GatewayTransactionService>;
pub type GetGatewayTransactionUseCase    = GetUseCase<GatewayTransaction, GatewayTransactionService>;
pub type DeleteGatewayTransactionUseCase = DeleteUseCase<GatewayTransaction, GatewayTransactionService>;
pub type ListGatewayTransactionUseCase   = ListUseCase<GatewayTransaction, GatewayTransactionService>;

// <<< CUSTOM
// END CUSTOM
