//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod gateway_transaction_usecases;
pub mod payment_gateway_provider_usecases;

pub use gateway_transaction_usecases::{
    CreateGatewayTransactionUseCase, UpdateGatewayTransactionUseCase, GetGatewayTransactionUseCase,
    DeleteGatewayTransactionUseCase, ListGatewayTransactionUseCase,
};
pub use payment_gateway_provider_usecases::{
    CreatePaymentGatewayProviderUseCase, UpdatePaymentGatewayProviderUseCase, GetPaymentGatewayProviderUseCase,
    DeletePaymentGatewayProviderUseCase, ListPaymentGatewayProviderUseCase,
};

// <<< CUSTOM
// END CUSTOM
