//! Use case type aliases for PaymentGatewayProvider aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreatePaymentGatewayProviderDto, UpdatePaymentGatewayProviderDto};
use crate::application::service::PaymentGatewayProviderService;
use crate::domain::entity::PaymentGatewayProvider;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreatePaymentGatewayProviderUseCase = CreateUseCase<PaymentGatewayProvider, CreatePaymentGatewayProviderDto, PaymentGatewayProviderService>;
pub type UpdatePaymentGatewayProviderUseCase = UpdateUseCase<PaymentGatewayProvider, UpdatePaymentGatewayProviderDto, PaymentGatewayProviderService>;
pub type GetPaymentGatewayProviderUseCase    = GetUseCase<PaymentGatewayProvider, PaymentGatewayProviderService>;
pub type DeletePaymentGatewayProviderUseCase = DeleteUseCase<PaymentGatewayProvider, PaymentGatewayProviderService>;
pub type ListPaymentGatewayProviderUseCase   = ListUseCase<PaymentGatewayProvider, PaymentGatewayProviderService>;

// <<< CUSTOM
// END CUSTOM
